USE [EFE_Core]
GO

/****** Object: Table [dbo].[Stocks] Script Date: 2/27/2025 12:01:52 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (1, 'Enphase Energy, Inc.', 'ENPH', 'Technology', 'Semiconductors', '$64891.47');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (2, 'Mistras Group Inc', 'MG', 'Consumer Services', 'Military/Government/Technical', '$24553.47');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (3, 'Pope Resources', 'POPE', 'Consumer Non-Durables', 'Environmental Services', '$22438.87');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (4, 'Bank of America Corporation', 'BAC^Y', 'Finance', 'Major Banks', '$99357.66');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (5, 'First Community Bancshares, Inc.', 'FCBC', 'Finance', 'Major Banks', '$80610.28');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (6, 'Lannett Co Inc', 'LCI', 'Health Care', 'Major Pharmaceuticals', '$82130.09');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (7, 'Acadia Healthcare Company, Inc.', 'ACHC', 'Health Care', 'Medical Specialities', '$52037.58');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (8, 'Arbor Realty Trust', 'ABR^A', 'n/a', 'n/a', '$63638.86');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (9, 'Automatic Data Processing, Inc.', 'ADP', 'Technology', 'EDP Services', '$20293.94');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (10, 'eHi Car Services Limited', 'EHIC', 'Consumer Services', 'Rental/Leasing Companies', '$91685.02');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (11, 'First Trust Emerging Markets Local Currency Bond ETF', 'FEMB', 'n/a', 'n/a', '$40137.46');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (12, 'Highland Funds I', 'NHF', 'n/a', 'n/a', '$37683.14');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (13, 'Blueknight Energy Partners L.P., L.L.C.', 'BKEPP', 'Energy', 'Natural Gas Distribution', '$79104.57');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (14, 'First Trust NASDAQ Clean Edge Green Energy Index Fund', 'QCLN', 'n/a', 'n/a', '$60229.37');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (15, 'RELX N.V.', 'RENX', 'Consumer Services', 'Publishing', '$96491.94');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (16, 'Alliqua BioMedical, Inc.', 'ALQA', 'Health Care', 'Medical/Dental Instruments', '$19984.60');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (17, 'Cabot Corporation', 'CBT', 'Basic Industries', 'Major Chemicals', '$46900.25');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (18, 'Global Indemnity Limited', 'GBLIL', 'Finance', 'Property-Casualty Insurers', '$32891.39');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (19, 'TCF Financial Corporation', 'TCF^C', 'n/a', 'n/a', '$92208.42');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (20, 'Layne Christensen Company', 'LAYN', 'Basic Industries', 'Engineering & Construction', '$26570.12');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (21, 'Destination Maternity Corporation', 'DEST', 'Consumer Services', 'Clothing/Shoe/Accessory Stores', '$8514.49');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (22, 'Nuveen Virginia Quality Municipal Income Fund', 'NPV', 'n/a', 'n/a', '$16450.79');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (23, 'Alcentra Capital Corp.', 'ABDC', 'n/a', 'n/a', '$46998.70');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (24, 'iShares GNMA Bond ETF', 'GNMA', 'n/a', 'n/a', '$33854.44');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (25, 'Capital Product Partners L.P.', 'CPLP', 'Transportation', 'Marine Transportation', '$23520.93');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (26, 'IBERIABANK Corporation', 'IBKCO', 'Finance', 'Major Banks', '$35052.78');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (27, 'Pzena Investment Management Inc', 'PZN', 'Finance', 'Investment Managers', '$77416.29');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (28, 'Bright Scholar Education Holdings Limited', 'BEDU', 'Consumer Services', 'Other Consumer Services', '$63644.35');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (29, 'PT Telekomunikasi Indonesia, Tbk', 'TLK', 'Public Utilities', 'Telecommunications Equipment', '$39155.56');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (30, 'VelocityShares 3x Inverse Gold ETN', 'DGLD', 'Finance', 'Investment Bankers/Brokers/Service', '$2636.22');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (31, 'LSI Industries Inc.', 'LYTS', 'Consumer Durables', 'Building Products', '$33134.07');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (32, 'Viavi Solutions Inc.', 'VIAV', 'Technology', 'Semiconductors', '$8875.39');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (33, 'Unifirst Corporation', 'UNF', 'Consumer Services', 'Other Consumer Services', '$51882.99');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (34, 'Viper Energy Partners LP', 'VNOM', 'Energy', 'Oil & Gas Production', '$7103.22');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (35, 'Lithia Motors, Inc.', 'LAD', 'Consumer Durables', 'Automotive Aftermarket', '$82075.41');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (36, 'Maiden Holdings, Ltd.', 'MHLD', 'Finance', 'Property-Casualty Insurers', '$62422.39');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (37, 'Source Capital, Inc.', 'SOR', 'n/a', 'n/a', '$47536.59');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (38, 'Avon Products, Inc.', 'AVP', 'Consumer Non-Durables', 'Package Goods/Cosmetics', '$2633.86');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (39, 'Daseke, Inc.', 'DSKE', 'Consumer Services', 'Transportation Services', '$80675.86');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (40, 'ARC Document Solutions, Inc.', 'ARC', 'Consumer Services', 'Professional Services', '$53431.59');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (41, 'VistaGen Therapeutics, Inc.', 'VTGN', 'Health Care', 'Major Pharmaceuticals', '$48751.84');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (42, 'Frontline Ltd.', 'FRO', 'Transportation', 'Marine Transportation', '$83763.65');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (43, 'AMC Entertainment Holdings, Inc.', 'AMC', 'Consumer Services', 'Movies/Entertainment', '$68368.11');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (44, 'Synthesis Energy Systems, Inc.', 'SYMX', 'Basic Industries', 'Major Chemicals', '$52758.10');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (45, 'RH', 'RH', 'Consumer Services', 'Other Specialty Stores', '$33279.67');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (46, 'Star Bulk Carriers Corp.', 'SBLKL', 'Transportation', 'Marine Transportation', '$83360.53');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (47, 'Nuveen Energy MLP Total Return Fund', 'JMF', 'n/a', 'n/a', '$30383.12');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (48, 'Cabot Corporation', 'CBT', 'Basic Industries', 'Major Chemicals', '$34829.40');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (49, 'TRI Pointe Group, Inc.', 'TPH', 'Capital Goods', 'Homebuilding', '$99982.50');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (50, 'Sterling Bancorp', 'STL', 'Finance', 'Major Banks', '$91389.87');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (51, 'Rosetta Stone', 'RST', 'Technology', 'Computer Software: Prepackaged Software', '$90223.43');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (52, 'Southern Missouri Bancorp, Inc.', 'SMBC', 'Finance', 'Banks', '$30168.01');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (53, 'Affiliated Managers Group, Inc.', 'AMG', 'Finance', 'Investment Managers', '$64898.49');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (54, 'OneMain Holdings, Inc.', 'OMF', 'Finance', 'Finance: Consumer Services', '$43490.92');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (55, 'GGP Inc.', 'GGP', 'Consumer Services', 'Real Estate Investment Trusts', '$1577.78');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (56, 'Entercom Communications Corporation', 'ETM', 'Consumer Services', 'Broadcasting', '$49594.13');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (57, 'Just Energy Group, Inc.', 'JE', 'Public Utilities', 'Oil/Gas Transmission', '$54302.01');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (58, 'POSCO', 'PKX', 'Basic Industries', 'Steel/Iron Ore', '$62436.54');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (59, 'Walt Disney Company (The)', 'DIS', 'Consumer Services', 'Television Services', '$45746.39');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (60, 'Chegg, Inc.', 'CHGG', 'Consumer Services', 'Other Consumer Services', '$90494.23');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (61, 'Soligenix, Inc.', 'SNGXW', 'Health Care', 'Major Pharmaceuticals', '$46893.65');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (62, 'BlueLinx Holdings Inc.', 'BXC', 'Capital Goods', 'Wholesale Distributors', '$10409.01');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (63, 'Identiv, Inc.', 'INVE', 'Technology', 'Computer peripheral equipment', '$64075.39');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (64, 'FB Financial Corporation', 'FBK', 'Finance', 'Major Banks', '$12862.88');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (65, 'Curis, Inc.', 'CRIS', 'Health Care', 'Biotechnology: Biological Products (No Diagnostic Substances)', '$70561.29');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (66, 'Twenty-First Century Fox, Inc.', 'FOXA', 'Consumer Services', 'Television Services', '$68090.76');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (67, 'Foundation Building Materials, Inc.', 'FBM', 'Consumer Services', 'RETAIL: Building Materials', '$53407.64');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (68, 'PIMCO Strategic Income Fund, Inc.', 'RCS', 'n/a', 'n/a', '$17092.66');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (69, 'Teladoc, Inc.', 'TDOC', 'Health Care', 'Medical/Nursing Services', '$28209.41');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (70, 'Great Elm Capital Group, Inc. ', 'GEC', 'Technology', 'Computer Software: Prepackaged Software', '$83517.71');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (71, 'Aradigm Corporation', 'ARDM', 'Health Care', 'Biotechnology: Electromedical & Electrotherapeutic Apparatus', '$17533.66');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (72, 'Active Alts Contrarian ETF', 'SQZZ', 'n/a', 'n/a', '$2000.34');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (73, 'Alaska Communications Systems Group, Inc.', 'ALSK', 'Public Utilities', 'Telecommunications Equipment', '$50978.57');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (74, 'Entergy Mississippi, Inc.', 'EMP', 'Public Utilities', 'Electric Utilities: Central', '$20956.27');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (75, 'Trupanion, Inc.', 'TRUP', 'Health Care', 'Medical Specialities', '$20419.77');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (76, 'Eldorado Gold Corporation', 'EGO', 'Basic Industries', 'Precious Metals', '$46040.84');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (77, 'Telephone and Data Systems, Inc.', 'TDI', 'Public Utilities', 'Telecommunications Equipment', '$40159.28');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (78, 'First Trust Enhanced Short Maturity ETF', 'FTSM', 'n/a', 'n/a', '$37043.94');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (79, 'Thai Fund, Inc. (The)', 'TTF', 'n/a', 'n/a', '$99366.42');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (80, 'Argo Group International Holdings, Ltd.', 'AGIIL', 'Finance', 'Specialty Insurers', '$46985.09');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (81, 'Ellington Residential Mortgage REIT', 'EARN', 'Consumer Services', 'Real Estate Investment Trusts', '$80417.75');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (82, 'Costamare Inc.', 'CMRE', 'Transportation', 'Marine Transportation', '$21015.76');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (83, 'Teleflex Incorporated', 'TFX', 'Health Care', 'Medical/Dental Instruments', '$45990.63');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (84, 'General Finance Corporation', 'GFN', 'Technology', 'Diversified Commercial Services', '$11759.00');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (85, 'AG Mortgage Investment Trust, Inc.', 'MITT^B', 'n/a', 'n/a', '$30592.70');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (86, 'Sunstone Hotel Investors, Inc.', 'SHO^F', 'n/a', 'n/a', '$34045.21');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (87, 'SilverSun Technologies, Inc.', 'SSNT', 'Miscellaneous', 'Business Services', '$75590.52');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (88, 'National Energy Services Reunited Corp.', 'NESRW', 'Finance', 'Business Services', '$14533.39');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (89, 'CYS Investments, Inc.', 'CYS^A', 'n/a', 'n/a', '$4542.83');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (90, 'Amira Nature Foods Ltd', 'ANFI', 'Consumer Non-Durables', 'Packaged Foods', '$25684.34');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (91, 'The Charles Schwab Corporation', 'SCHW^B', 'n/a', 'n/a', '$61020.45');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (92, 'Charles River Laboratories International, Inc.', 'CRL', 'Health Care', 'Biotechnology: Commercial Physical & Biological Resarch', '$53530.07');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (93, 'Seaspan Corporation', 'SSWN', 'Transportation', 'Marine Transportation', '$39898.98');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (94, 'Comfort Systems USA, Inc.', 'FIX', 'Capital Goods', 'Engineering & Construction', '$66952.16');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (95, 'ScanSource, Inc.', 'SCSC', 'Technology', 'Retail: Computer Software & Peripheral Equipment', '$69006.98');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (96, 'Enterprise Financial Services Corporation', 'EFSC', 'Finance', 'Major Banks', '$17103.89');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (97, 'Woodward, Inc.', 'WWD', 'Energy', 'Industrial Machinery/Components', '$64593.25');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (98, 'Methode Electronics, Inc.', 'MEI', 'Capital Goods', 'Electrical Products', '$30718.52');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (99, 'Independent Bank Group, Inc', 'IBTX', 'Finance', 'Major Banks', '$59134.81');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (100, 'Globus Maritime Limited', 'GLBS', 'Transportation', 'Marine Transportation', '$2023.06');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (101, 'Myriad Genetics, Inc.', 'MYGN', 'Health Care', 'Biotechnology: In Vitro & In Vivo Diagnostic Substances', '$20076.05');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (102, 'TIM Participacoes S.A.', 'TSU', 'Public Utilities', 'Telecommunications Equipment', '$61493.12');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (103, 'Malibu Boats, Inc.', 'MBUU', 'Capital Goods', 'Marine Transportation', '$42404.14');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (104, 'Capitala Finance Corp.', 'CPTA', 'n/a', 'n/a', '$95336.73');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (105, 'Knowles Corporation', 'KN', 'Consumer Non-Durables', 'Consumer Electronics/Appliances', '$21732.95');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (106, 'Southern Company (The)', 'SOJB', 'Public Utilities', 'Electric Utilities: Central', '$68259.80');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (107, 'Advantage Oil & Gas Ltd', 'AAV', 'Energy', 'Oil & Gas Production', '$1752.91');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (108, 'Trustmark Corporation', 'TRMK', 'Finance', 'Major Banks', '$67386.12');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (109, 'LegacyTexas Financial Group, Inc.', 'LTXB', 'Finance', 'Savings Institutions', '$35852.44');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (110, 'HopFed Bancorp, Inc.', 'HFBC', 'Finance', 'Major Banks', '$57543.72');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (111, 'China Rapid Finance Limited', 'XRF', 'Finance', 'Finance: Consumer Services', '$79170.39');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (112, 'Huntington Bancshares Incorporated', 'HBANN', 'Finance', 'Major Banks', '$25399.77');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (113, 'Digirad Corporation', 'DRAD', 'Health Care', 'Biotechnology: Electromedical & Electrotherapeutic Apparatus', '$88620.56');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (114, 'Eagle Growth and Income Opportunities Fund', 'EGIF', 'n/a', 'n/a', '$44547.96');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (115, 'LM Funding America, Inc.', 'LMFAW', 'Finance', 'Finance: Consumer Services', '$18703.12');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (116, 'Consolidated Communications Holdings, Inc.', 'CNSL', 'Public Utilities', 'Telecommunications Equipment', '$90398.27');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (117, 'VictoryShares US Large Cap High Div Volatility Wtd ETF', 'CDL', 'n/a', 'n/a', '$10026.35');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (118, 'GlassBridge Enterprises, Inc.', 'GLA', 'Technology', 'Electronic Components', '$94336.90');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (119, 'Catalent, Inc.', 'CTLT', 'Health Care', 'Major Pharmaceuticals', '$61726.38');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (120, 'USA Technologies, Inc.', 'USATP', 'Miscellaneous', 'Office Equipment/Supplies/Services', '$23174.92');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (121, 'Lightbridge Corporation', 'LTBR', 'Consumer Services', 'Professional Services', '$6826.42');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (122, 'Ikonics Corporation', 'IKNX', 'Miscellaneous', 'Industrial Machinery/Components', '$6736.89');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (123, 'Reata Pharmaceuticals, Inc.', 'RETA', 'Health Care', 'Major Pharmaceuticals', '$80387.17');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (124, 'Lockheed Martin Corporation', 'LMT', 'Capital Goods', 'Military/Government/Technical', '$45024.76');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (125, 'Urban Outfitters, Inc.', 'URBN', 'Consumer Services', 'Clothing/Shoe/Accessory Stores', '$14019.81');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (126, 'Hi-Crush Partners LP', 'HCLP', 'Basic Industries', 'Mining & Quarrying of Nonmetallic Minerals (No Fuels)', '$85297.28');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (127, 'Global Brokerage, Inc.', 'GLBR', 'Finance', 'Investment Bankers/Brokers/Service', '$60921.73');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (128, 'Global Payments Inc.', 'GPN', 'Miscellaneous', 'Business Services', '$55543.18');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (129, 'Sunoco LP', 'SUN', 'Energy', 'Oil Refining/Marketing', '$85154.02');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (130, 'Kilroy Realty Corporation', 'KRC^H', 'n/a', 'n/a', '$97511.67');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (131, 'Profire Energy, Inc.', 'PFIE', 'Energy', 'Metal Fabrications', '$90498.70');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (132, 'Reinsurance Group of America, Incorporated', 'RGA', 'Finance', 'Life Insurance', '$39162.27');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (133, 'National Health Investors, Inc.', 'NHI', 'Consumer Services', 'Real Estate Investment Trusts', '$26489.20');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (134, 'Kennedy-Wilson Holdings Inc.', 'KW', 'Finance', 'Real Estate', '$3611.86');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (135, 'The Kraft Heinz Company', 'KHC', 'Consumer Non-Durables', 'Packaged Foods', '$37371.77');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (136, 'Five Oaks Investment Corp.', 'OAKS^A', 'n/a', 'n/a', '$71358.88');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (137, 'M&T Bank Corporation', 'MTB^C', 'n/a', 'n/a', '$58846.24');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (138, 'First Trust United Kingdom AlphaDEX Fund', 'FKU', 'n/a', 'n/a', '$36714.63');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (139, 'ACNB Corporation', 'ACNB', 'Finance', 'Major Banks', '$93353.31');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (140, 'Materialise NV', 'MTLS', 'Technology', 'Computer Software: Prepackaged Software', '$30342.41');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (141, 'InterDigital, Inc.', 'IDCC', 'Miscellaneous', 'Multi-Sector Companies', '$58144.18');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (142, 'Exactech, Inc.', 'EXAC', 'Health Care', 'Industrial Specialties', '$35324.16');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (143, 'FuelCell Energy, Inc.', 'FCEL', 'Miscellaneous', 'Industrial Machinery/Components', '$89486.65');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (144, 'Hersha Hospitality Trust', 'HT^C', 'n/a', 'n/a', '$59545.68');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (145, 'Bemis Company, Inc.', 'BMS', 'Consumer Durables', 'Containers/Packaging', '$96239.77');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (146, 'Jabil Inc.', 'JBL', 'Technology', 'Electrical Products', '$84264.77');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (147, 'American National Bankshares, Inc.', 'AMNB', 'Finance', 'Major Banks', '$41079.77');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (148, 'DAVIDsTEA Inc.', 'DTEA', 'Consumer Non-Durables', 'Food Chains', '$25875.38');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (149, 'Capital One Financial Corporation', 'COF.WS', 'n/a', 'n/a', '$32494.17');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (150, 'Aberdeen Greater China Fund, Inc.', 'GCH', 'n/a', 'n/a', '$80340.11');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (151, 'ServiceNow, Inc.', 'NOW', 'Technology', 'Computer Software: Prepackaged Software', '$55207.56');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (152, 'Penns Woods Bancorp, Inc.', 'PWOD', 'Finance', 'Major Banks', '$25980.01');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (153, 'Eaton Vance Tax-Managed Diversified Equity Income Fund', 'ETY', 'n/a', 'n/a', '$70387.25');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (154, 'Knight Transportation, Inc.', 'KNX', 'Transportation', 'Trucking Freight/Courier Services', '$86599.96');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (155, 'The Providence Service Corporation', 'PRSC', 'Consumer Services', 'Transportation Services', '$68016.64');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (156, 'China Eastern Airlines Corporation Ltd.', 'CEA', 'Transportation', 'Air Freight/Delivery Services', '$70440.09');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (157, 'Solar Capital Ltd.', 'SLRC', 'n/a', 'n/a', '$38753.97');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (158, 'Actua Corporation', 'ACTA', 'Technology', 'EDP Services', '$88564.06');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (159, 'NextEra Energy, Inc.', 'NEE', 'Public Utilities', 'Electric Utilities: Central', '$56008.71');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (160, 'Dynatronics Corporation', 'DYNT', 'Health Care', 'Biotechnology: Electromedical & Electrotherapeutic Apparatus', '$83072.09');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (161, 'Boulevard Acquisition Corp. II', 'BLVD', 'Finance', 'Business Services', '$61757.86');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (162, 'NxStage Medical, Inc.', 'NXTM', 'Health Care', 'Biotechnology: Electromedical & Electrotherapeutic Apparatus', '$21549.23');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (163, 'Clear Channel Outdoor Holdings, Inc.', 'CCO', 'Consumer Services', 'Advertising', '$19806.11');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (164, 'Federal Agricultural Mortgage Corporation', 'AGM^B', 'n/a', 'n/a', '$86128.07');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (165, 'Ryanair Holdings plc', 'RYAAY', 'Transportation', 'Air Freight/Delivery Services', '$52400.59');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (166, 'J P Morgan Chase & Co', 'JPM^G', 'n/a', 'n/a', '$21822.77');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (167, 'Cutera, Inc.', 'CUTR', 'Health Care', 'Biotechnology: Electromedical & Electrotherapeutic Apparatus', '$43930.41');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (168, 'Fiat Chrysler Automobiles N.V.', 'FCAU', 'Capital Goods', 'Auto Manufacturing', '$79777.76');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (169, 'Cenovus Energy Inc', 'CVE', 'Energy', 'Oil & Gas Production', '$22942.37');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (170, 'Soligenix, Inc.', 'SNGX', 'Health Care', 'Major Pharmaceuticals', '$80723.20');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (171, 'First Trust NASDAQ ABA Community Bank Index Fund', 'QABA', 'n/a', 'n/a', '$23166.08');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (172, 'National General Holdings Corp', 'NGHC', 'Finance', 'Property-Casualty Insurers', '$79204.73');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (173, 'Sonoma Pharmaceuticals, Inc.', 'SNOA', 'Health Care', 'Major Pharmaceuticals', '$26027.74');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (174, 'Ovid Therapeutics Inc.', 'OVID', 'Health Care', 'Major Pharmaceuticals', '$30064.41');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (175, 'TIM Participacoes S.A.', 'TSU', 'Public Utilities', 'Telecommunications Equipment', '$63192.76');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (176, 'MetLife, Inc.', 'MET^A', 'n/a', 'n/a', '$33032.31');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (177, 'Coherent, Inc.', 'COHR', 'Capital Goods', 'Biotechnology: Laboratory Analytical Instruments', '$94685.21');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (178, 'First Trust International Multi-Asset Diversified Income Index', 'YDIV', 'n/a', 'n/a', '$81986.39');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (179, 'Innoviva, Inc.', 'INVA', 'Health Care', 'Major Pharmaceuticals', '$21600.87');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (180, 'DTE Energy Company', 'DTY', 'Public Utilities', 'Electric Utilities: Central', '$13664.58');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (181, 'NextEra Energy, Inc.', 'NEE^Q', 'n/a', 'n/a', '$19869.22');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (182, 'Landmark Infrastructure Partners LP', 'LMRK', 'Consumer Services', 'Real Estate', '$90197.98');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (183, 'Eco-Stim Energy Solutions, Inc.', 'ESES', 'Energy', 'Oilfield Services/Equipment', '$47427.28');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (184, 'Kadant Inc', 'KAI', 'Technology', 'Industrial Machinery/Components', '$23675.52');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (185, 'Mammoth Energy Services, Inc.', 'TUSK', 'Energy', 'Oilfield Services/Equipment', '$27916.76');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (186, 'TechTarget, Inc.', 'TTGT', 'Miscellaneous', 'Business Services', '$17113.17');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (187, 'Virtus Investment Partners, Inc.', 'VRTS', 'Finance', 'Investment Managers', '$48278.15');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (188, 'Exxon Mobil Corporation', 'XOM', 'Energy', 'Integrated oil Companies', '$64830.05');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (189, 'Raytheon Company', 'RTN', 'Capital Goods', 'Industrial Machinery/Components', '$28077.90');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (190, 'Handy & Harman Ltd.', 'HNH', 'Capital Goods', 'Industrial Specialties', '$20745.79');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (191, 'The GDL Fund', 'GDL^B', 'n/a', 'n/a', '$89906.11');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (192, 'Equinix, Inc.', 'EQIX', 'Consumer Services', 'Real Estate Investment Trusts', '$67410.08');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (193, 'Littelfuse, Inc.', 'LFUS', 'Consumer Durables', 'Electrical Products', '$49372.65');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (194, 'J P Morgan Chase & Co', 'JPM^A', 'Finance', 'Major Banks', '$9872.24');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (195, 'VOC Energy Trust', 'VOC', 'Energy', 'Oil & Gas Production', '$65241.55');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (196, 'LightInTheBox Holding Co., Ltd.', 'LITB', 'Consumer Services', 'Catalog/Specialty Distribution', '$58873.41');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (197, 'Materialise NV', 'MTLS', 'Technology', 'Computer Software: Prepackaged Software', '$88787.10');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (198, 'BOK Financial Corporation', 'BOKF', 'Finance', 'Major Banks', '$22107.84');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (199, 'Burcon NutraScience Corp', 'BUR', 'Consumer Non-Durables', 'Packaged Foods', '$66788.41');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (200, 'Granite Real Estate Inc.', 'GRP.U', 'n/a', 'n/a', '$83164.07');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (201, 'Prudential Public Limited Company', 'PUK', 'Finance', 'Life Insurance', '$4885.15');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (202, 'Vantage Energy Acquisition Corp.', 'VEACU', 'Finance', 'Business Services', '$3974.42');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (203, 'Torchlight Energy Resources, Inc.', 'TRCH', 'Energy', 'Oil & Gas Production', '$67844.95');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (204, 'Macatawa Bank Corporation', 'MCBC', 'Finance', 'Major Banks', '$91356.08');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (205, 'Costamare Inc.', 'CMRE^D', 'n/a', 'n/a', '$60883.94');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (206, 'Steel Partners Holdings LP', 'SPLP', 'Capital Goods', 'Industrial Specialties', '$39903.52');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (207, 'C.R. Bard, Inc.', 'BCR', 'Health Care', 'Medical/Dental Instruments', '$86023.77');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (208, 'Eaton Vance Tax-Managed Global Diversified Equity Income Fund', 'EXG', 'n/a', 'n/a', '$67101.34');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (209, 'LTC Properties, Inc.', 'LTC', 'Consumer Services', 'Real Estate Investment Trusts', '$73947.86');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (210, 'Sears Holdings Corporation', 'SHLDW', 'Consumer Services', 'Department/Specialty Retail Stores', '$50267.05');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (211, 'Liberty Interactive Corporation', 'LVNTA', 'Consumer Services', 'Catalog/Specialty Distribution', '$45097.17');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (212, 'ARC Document Solutions, Inc.', 'ARC', 'Consumer Services', 'Professional Services', '$10340.28');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (213, 'Lehman ABS Corporation', 'KTH', 'Finance', 'Finance: Consumer Services', '$38176.08');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (214, 'Autoliv, Inc.', 'ALV', 'Capital Goods', 'Auto Parts:O.E.M.', '$10732.41');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (215, 'MMA Capital Management, LLC', 'MMAC', 'Finance', 'Real Estate', '$74248.07');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (216, 'Paychex, Inc.', 'PAYX', 'Consumer Services', 'Diversified Commercial Services', '$52507.03');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (217, 'Mackinac Financial Corporation', 'MFNC', 'Finance', 'Major Banks', '$85945.35');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (218, 'The Joint Corp.', 'JYNT', 'Miscellaneous', 'Multi-Sector Companies', '$16227.63');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (219, 'China Automotive Systems, Inc.', 'CAAS', 'Capital Goods', 'Auto Parts:O.E.M.', '$78114.69');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (220, 'Nokia Corporation', 'NOK', 'Technology', 'Radio And Television Broadcasting And Communications Equipment', '$80953.27');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (221, 'AMN Healthcare Services Inc', 'AMN', 'Technology', 'Professional Services', '$70337.60');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (222, 'Integer Holdings Corporation', 'ITGR', 'Miscellaneous', 'Industrial Machinery/Components', '$52698.13');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (223, 'Goldman Sachs Group, Inc. (The)', 'GS^J', 'n/a', 'n/a', '$83861.61');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (224, 'Axar Acquisition Corp.', 'AXARW', 'Finance', 'Business Services', '$70933.28');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (225, 'Bank of the Ozarks', 'OZRK', 'Finance', 'Major Banks', '$80561.04');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (226, 'Adams Diversified Equity Fund, Inc.', 'ADX', 'n/a', 'n/a', '$15650.80');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (227, 'Discovery Communications, Inc.', 'DISCK', 'Consumer Services', 'Television Services', '$15353.81');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (228, 'Egalet Corporation', 'EGLT', 'Health Care', 'Major Pharmaceuticals', '$60690.38');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (229, 'GATX Corporation', 'GATX', 'Consumer Services', 'Transportation Services', '$35174.16');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (230, 'Mercury Systems Inc', 'MRCY', 'Capital Goods', 'Electrical Products', '$70443.34');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (231, 'IXYS Corporation', 'IXYS', 'Technology', 'Semiconductors', '$13899.62');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (232, 'C.R. Bard, Inc.', 'BCR', 'Health Care', 'Medical/Dental Instruments', '$40255.33');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (233, 'Electrum Special Acquisition Corporation', 'ELECU', 'Finance', 'Business Services', '$68665.52');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (234, 'Summit Materials, Inc.', 'SUM', 'Basic Industries', 'Mining & Quarrying of Nonmetallic Minerals (No Fuels)', '$63236.65');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (235, 'American Software, Inc.', 'AMSWA', 'Technology', 'Computer Software: Prepackaged Software', '$35837.24');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (236, 'West Marine, Inc.', 'WMAR', 'Consumer Durables', 'Automotive Aftermarket', '$74192.38');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (237, 'Weight Watchers International Inc', 'WTW', 'Consumer Services', 'Other Consumer Services', '$38972.42');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (238, 'Colony Bankcorp, Inc.', 'CBAN', 'Finance', 'Major Banks', '$58894.29');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (239, 'PowerShares DWA Momentum Portfolio', 'PDP', 'n/a', 'n/a', '$65446.47');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (240, 'Athersys, Inc.', 'ATHX', 'Health Care', 'Major Pharmaceuticals', '$33274.45');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (241, 'Intercontinental Hotels Group', 'IHG', 'Consumer Services', 'Hotels/Resorts', '$2962.05');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (242, 'BroadSoft, Inc.', 'BSFT', 'Technology', 'Computer Software: Prepackaged Software', '$3117.10');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (243, 'Genius Brands International, Inc.', 'GNUS', 'Consumer Services', 'Movies/Entertainment', '$27615.54');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (244, 'TCF Financial Corporation', 'TCF^C', 'n/a', 'n/a', '$32887.91');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (245, 'Eaton vance Floating-Rate Income Plus Fund', 'EFF', 'n/a', 'n/a', '$90654.62');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (246, 'Ecolab Inc.', 'ECL', 'Basic Industries', 'Package Goods/Cosmetics', '$29682.29');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (247, 'U.S. Bancorp', 'USB^H', 'n/a', 'n/a', '$76731.61');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (248, 'FIRST REPUBLIC BANK', 'FRC', 'n/a', 'n/a', '$63276.09');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (249, 'Maximus, Inc.', 'MMS', 'Miscellaneous', 'Business Services', '$66038.37');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (250, 'TICC Capital Corp.', 'TICC', 'n/a', 'n/a', '$11662.01');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (251, 'Public Storage', 'PSA^A', 'n/a', 'n/a', '$93997.23');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (252, 'Nam Tai Property Inc.', 'NTP', 'Finance', 'Real Estate', '$67876.50');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (253, 'Pembina Pipeline Corp.', 'PBA', 'Energy', 'Oil & Gas Production', '$8043.61');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (254, 'Terra Nitrogen Company, L.P.', 'TNH', 'Basic Industries', 'Agricultural Chemicals', '$7438.41');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (255, 'Mota Group, Inc.', 'MOTA', 'n/a', 'n/a', '$13172.39');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (256, 'Bio-Path Holdings, Inc.', 'BPTH', 'Health Care', 'Major Pharmaceuticals', '$52189.35');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (257, 'HSBC Holdings plc', 'HSBC', 'Finance', 'Savings Institutions', '$68119.01');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (258, 'Performance Food Group Company', 'PFGC', 'Consumer Non-Durables', 'Food Distributors', '$91612.25');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (259, 'PowerShares KBW Bank Portfolio', 'KBWB', 'n/a', 'n/a', '$65295.73');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (260, 'HomeStreet, Inc.', 'HMST', 'Finance', 'Major Banks', '$90851.12');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (261, 'Ritter Pharmaceuticals, Inc.', 'RTTR', 'Health Care', 'Major Pharmaceuticals', '$17340.66');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (262, 'ZAGG Inc', 'ZAGG', 'Consumer Services', 'Other Specialty Stores', '$44051.33');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (263, 'Summit Midstream Partners, LP', 'SMLP', 'Public Utilities', 'Natural Gas Distribution', '$44827.30');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (264, 'Flowers Foods, Inc.', 'FLO', 'Consumer Non-Durables', 'Packaged Foods', '$14077.65');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (265, 'Acco Brands Corporation', 'ACCO', 'Consumer Durables', 'Publishing', '$24524.37');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (266, 'Honeywell International Inc.', 'HON', 'Capital Goods', 'Auto Parts:O.E.M.', '$65525.47');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (267, 'Empire State Realty Trust, Inc.', 'ESRT', 'Consumer Services', 'Real Estate Investment Trusts', '$94239.20');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (268, 'Employers Holdings Inc', 'EIG', 'Finance', 'Property-Casualty Insurers', '$94980.51');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (269, 'Concurrent Computer Corporation', 'CCUR', 'Technology', 'Computer Manufacturing', '$50377.42');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (270, 'TransMontaigne Partners L.P.', 'TLP', 'Energy', 'Natural Gas Distribution', '$10302.71');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (271, 'American Financial Group, Inc.', 'AFA', 'Finance', 'Property-Casualty Insurers', '$20627.85');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (272, 'Coca-Cola Bottling Co. Consolidated', 'COKE', 'Consumer Non-Durables', 'Beverages (Production/Distribution)', '$46941.28');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (273, 'Emergent Biosolutions, Inc.', 'EBS', 'Health Care', 'Major Pharmaceuticals', '$41122.13');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (274, 'Principal U.S. Small Cap Index ETF', 'PSC', 'n/a', 'n/a', '$56031.95');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (275, 'iPath US Treasury Long Bond Bear ETN', 'DLBS', 'Finance', 'Commercial Banks', '$7759.14');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (276, 'JAKKS Pacific, Inc.', 'JAKK', 'Consumer Non-Durables', 'Recreational Products/Toys', '$98701.96');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (277, 'Double Eagle Acquisition Corp.', 'EAGL', 'Finance', 'Business Services', '$38734.73');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (278, 'Nuveen Connecticut Quality Municipal Income Fund', 'NTC', 'n/a', 'n/a', '$46597.53');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (279, 'WSFS Financial Corporation', 'WSFS', 'Finance', 'Major Banks', '$55350.62');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (280, 'Echelon Corporation', 'ELON', 'Technology', 'Computer Communications Equipment', '$66659.78');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (281, 'PNM Resources, Inc. (Holding Co.)', 'PNM', 'Public Utilities', 'Electric Utilities: Central', '$74483.13');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (282, 'Vince Holding Corp.', 'VNCE', 'Consumer Services', 'Clothing/Shoe/Accessory Stores', '$5328.89');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (283, 'Allete, Inc.', 'ALE', 'Public Utilities', 'Power Generation', '$33547.71');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (284, 'First Potomac Realty Trust', 'FPO', 'Consumer Services', 'Real Estate Investment Trusts', '$86247.14');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (285, 'Gabelli Global Small and Mid Cap Value Trust (The)', 'GGZ', 'n/a', 'n/a', '$1931.27');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (286, 'American Homes 4 Rent', 'AMH^E', 'n/a', 'n/a', '$61936.55');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (287, 'JPMorgan China Region Fund, Inc.', 'JFC', 'n/a', 'n/a', '$59145.62');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (288, 'Teekay Offshore Partners L.P.', 'TOO^B', 'n/a', 'n/a', '$38150.46');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (289, 'Oak Valley Bancorp (CA)', 'OVLY', 'Finance', 'Major Banks', '$11977.05');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (290, 'NextEra Energy, Inc.', 'NEE^H', 'n/a', 'n/a', '$18095.89');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (291, 'Paratek Pharmaceuticals, Inc. ', 'PRTK', 'Health Care', 'Major Pharmaceuticals', '$40717.96');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (292, 'Dime Community Bancshares, Inc.', 'DCOM', 'Finance', 'Savings Institutions', '$21951.61');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (293, 'Canon, Inc.', 'CAJ', 'Miscellaneous', 'Industrial Machinery/Components', '$82268.40');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (294, 'Intrexon Corporation', 'XON', 'Health Care', 'Biotechnology: Commercial Physical & Biological Resarch', '$74805.70');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (295, 'Super Micro Computer, Inc.', 'SMCI', 'Technology', 'Computer Manufacturing', '$18768.99');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (296, 'Hostess Brands, Inc.', 'TWNKW', 'Consumer Non-Durables', 'Packaged Foods', '$76241.72');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (297, 'Columbus McKinnon Corporation', 'CMCO', 'Capital Goods', 'Construction/Ag Equipment/Trucks', '$88058.52');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (298, 'Cimpress N.V', 'CMPR', 'Miscellaneous', 'Publishing', '$42352.88');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (299, 'Hawaiian Telcom Holdco, Inc.', 'HCOM', 'Consumer Services', 'Telecommunications Equipment', '$24178.99');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (300, 'Huntington Bancshares Incorporated', 'HBAN', 'Finance', 'Major Banks', '$65658.02');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (301, 'Luminex Corporation', 'LMNX', 'Health Care', 'Medical/Dental Instruments', '$50250.50');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (302, 'Nuveen Credit Strategies Income Fund', 'JQC', 'n/a', 'n/a', '$65510.79');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (303, 'ENI S.p.A.', 'E', 'Energy', 'Oil & Gas Production', '$2014.56');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (304, 'Envestnet, Inc', 'ENV', 'Miscellaneous', 'Business Services', '$65922.86');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (305, 'Western Asset Global High Income Fund Inc', 'EHI', 'n/a', 'n/a', '$69076.48');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (306, 'Osisko Gold Royalties Ltd', 'OR', 'Basic Industries', 'Precious Metals', '$49368.02');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (307, 'CIT Group Inc (DEL)', 'CIT', 'Finance', 'Finance: Consumer Services', '$45947.48');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (308, 'Nuveen Floating Rate Income Fund', 'JFR', 'n/a', 'n/a', '$7258.57');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (309, 'Altisource Residential Corporation', 'RESI', 'Finance', 'Real Estate', '$19442.70');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (310, 'EPR Properties', 'EPR^F', 'n/a', 'n/a', '$5770.07');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (311, 'Brookfield Property Partners L.P.', 'BPY', 'Finance', 'Real Estate', '$25722.00');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (312, 'Mattel, Inc.', 'MAT', 'Consumer Non-Durables', 'Recreational Products/Toys', '$53370.33');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (313, 'Shopify Inc.', 'SHOP', 'Technology', 'Computer Software: Prepackaged Software', '$74720.62');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (314, 'United Continental Holdings, Inc.', 'UAL', 'Transportation', 'Air Freight/Delivery Services', '$93262.90');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (315, 'Seaspan Corporation', 'SSW', 'Transportation', 'Marine Transportation', '$21603.24');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (316, 'Unilever PLC', 'UL', 'Basic Industries', 'Package Goods/Cosmetics', '$40919.74');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (317, 'Halyard Health, Inc.', 'HYH', 'Health Care', 'Industrial Specialties', '$40048.16');
insert into Stocks (id, Name, Symbol, Sector, Industry , Balance) values (318, 'Two Harbors Investments Corp', 'TWO^A', 'n/a', 'n/a', '$25870.52');